run1: 
	ozc -c test1.oz && ozengine test1.ozf && rm test1.ozf

run2: 
	ozc -c test2and3.oz && ozengine test2and3.ozf && rm test2and3.ozf

run4:
	ozc -c test4.oz && ozengine test4.ozf && rm test4.ozf

run5:
	ozc -c test5.oz && ozengine test5.ozf && rm test5.ozf

run6:
	ozc -c test6.oz && ozengine test6.ozf && rm test6.ozf